---
title: "Bootstrapping CPUE"
author: "Lucas A. Nell"
date: "March 31, 2016"
output:
  html_document:
    highlight: haddock
    theme: journal
  pdf_document:
    highlight: haddock
    latex_engine: xelatex
geometry: margin=1in
fontsize: 12pt
mainfont: Helvetica
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
```


```{r preamble}
library('dplyr')
library('readxl')
library('ggplot2')
library('boot')
library('broom')
library('RColorBrewer')

# Function to specify type of bootstrapping and simulations in ggplot2 plots
ggBootCI <- function(x, B = 1e4, CI_method = 'bca'){
  # These methods have full-length versions for their output list names
  if (method %in% c('norm', 'stud', 'perc')){
    outListMethod <- gsub('norm', 'normal', method) %>%
      gsub('stud', 'student', .) %>%
      gsub('perc', 'percent', .)
  } else {
    outListMethod <- method
  }
  
  bt.mean <- function(x, ind){
    return(c(mean(x[ind]),
             var(x[ind])/length(ind)))}
  inner.boot <- boot(x, statistic=bt.mean, R=B)
  
  # If all resamples return the same value, output df will be simply that value x3
  if (diff(range(inner.boot$t)) == 0){
    result <- data.frame(ymin = range(inner.boot$t)[1], 
                         y = range(inner.boot$t)[1], 
                         ymax = range(inner.boot$t)[1])
  } else {
  # If not, then run `boot.ci` from `boot` package
    inner.ci <- boot.ci(inner.boot, type=paste(method))
    result_tmp <- rev(inner.ci[[outListMethod]])[c(2,1)]
    result <- data.frame(ymin = result_tmp[1], 
                         y = median(inner.boot$t), 
                         ymax = result_tmp[2])
  }
  return(result)
}
```

```{r inputData}
RGSM_CPUE <- read_excel("brett_example.xlsx",1) %>% 
  rename(Area = `Effort m^2`, Count = SumOfSPEC) %>%
  filter(Year %in% 1993:2013, !is.na(Year), Month == 10, !is.na(Month)) %>%
  select(Year, Month, Station, Count, Area) %>%
  mutate(CPUE = (Count/Area)*100) %>% 
  arrange(Year)
```

```{r bootstrappingFuns}
# Function to sample row numbers from a numeric vector of sample sizes by group
stratSample <- function(group_n){
  
  ends <- cumsum(group_n)
  starts <- c(1, ends[-length(ends)] - 1)
  
  unlist(lapply(seq(length(ends)), function(i){
    sample(seq(starts[i], ends[i]), replace = TRUE)}))
}

# To open an issue on broom's GitHub: https://github.com/dgrtwo/broom

# Tweaking broom::bootstrap function to allow for seamless bootstrapping stratified by 
# a group (in this case, the 'Year' column)
stratBootstrap <- function(df, m, group) {
  
  df <- df %>% arrange_(group)
  
  n <- nrow(df)
  group_n <- (df %>% 
    group_by_(group) %>% 
    summarize(n = length(CPUE)))[['n']]
  
  attr(df, "indices") <- replicate(m, stratSample(group_n) - 1, 
                                   simplify = FALSE)
  attr(df, "drop") <- TRUE
  attr(df, "group_sizes") <- rep(n, m)
  attr(df, "biggest_group_size") <- n
  attr(df, "labels") <- data.frame(replicate = 1:m)
  attr(df, "vars") <- list(quote(replicate))
  class(df) <- c("grouped_df", "tbl_df", "tbl", "data.frame")
  
  df
}


```





```{r bootstrapping}
# Bootstrapping mean CPUE values
set.seed(9721)
CPUE_boot <- RGSM_CPUE %>%
  stratBootstrap(1000, group = 'Year') %>%
  do(summarize(group_by(., Year), CPUE = mean(CPUE))) %>% 
  # To strip attributes:
  as.data.frame %>% as.tbl

CPUE_bootSumm <- CPUE_boot %>%
  group_by(Year) %>%
  summarise(low = quantile(CPUE, probs = 0.025),
            mid = quantile(CPUE, probs = 0.5),
            high = quantile(CPUE, probs = 0.975))

CPUE_bootSumm
```

```{r plots}

# Minimal ggplot2 theme
plotTheme <- function(base_size = 10, base_family = 'Helvetica') {
  theme_minimal(base_size = base_size, base_family = base_family) %+replace%
    theme(
      strip.text = element_text(face = 'bold'),
      panel.grid.minor = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_line(color = 'gray50', size = 0.125, linetype = 3),
      panel.border = element_rect(fill = NA, color = "gray50"),
      axis.ticks = element_line(color = "gray50"),
      axis.ticks.length = unit(2, 'points'),
      legend.position = 'none'
    )
}

# Color palette for Year
myPalette <- RGSM_CPUE$Year %>% 
  unique %>% length %>% 
  colorRampPalette(brewer.pal(8,  'Dark2'))(.)


bootPlot <- RGSM_CPUE %>%
  ggplot(aes(x = factor(Year), y = CPUE, color = factor(Year))) +
  plotTheme() +
  scale_y_continuous(expression(Mean ~ Catch ~ 100 ~ m^{-2}), trans = 'log10',
                     breaks = c(0.001, 0.01, 0.1, 1, 10, 100, 1000), 
                     limits = c(0.001, 1000),
                     labels = function(n){format(n, scientific = FALSE, 
                                                 drop0trailing = TRUE)}) +
  scale_x_discrete('Year', breaks = seq(min(RGSM_CPUE$Year), max(RGSM_CPUE$Year))) +
  scale_color_manual(values = myPalette)

bootPlot +
  # geom_point(position = position_jitter(width = 0.3, height = 0), 
  #            alpha = 0.4, shape = 16) + 
  # stat_summary(fun.data = "ggBootCI",
  #              fun.args = list(B = 1e4, method = 'perc'),
  #              geom = "errorbar", width = 0.25, size = 0.75) +
  geom_errorbar(data = CPUE_bootSumm, inherit.aes = FALSE, 
                aes(ymin = low, ymax = high, x = factor(Year), 
                    color = factor(Year)),
                width = 0.25, size = 0.75) +
  geom_point(data = CPUE_bootSumm, aes(y = mid), 
             shape = 23, size = 3)


```


```{r testing}









```







